#############################################
#	Dual License: BSD-3-Clause AND MPL-2.0	#
#	Copyright (c) 2024, Adam Nogowski		#
#############################################

site_name: pytest-mark-count
site_description: Get a count of the number of tests marked, unmarked, and unique tests if tests have multiple markers
site_author: Adam Nogowski

theme: readthedocs

repo_url: https://github.com/anogowski/pytest-mark-count

pages:
- Home: index.md
