#############################################
#	Dual License: BSD-3-Clause AND MPL-2.0	#
#	Copyright (c) 2024, Adam Nogowski		#
#############################################

[tool.pytest.ini_options]
markers = [
	"it: Integration Tests",
	"rt: Regression Tests",
	"vt: Verification Tests",
]
addopts = "--collect-only"
